#if !canImport(ObjectiveC)
import XCTest

extension AtomicSheetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AtomicSheetTests = [
        ("testManyAppend", testManyAppend),
        ("testManyAppendAndInsert", testManyAppendAndInsert),
        ("testManyDelete", testManyDelete),
        ("testMove", testMove),
    ]
}

extension AuthenticationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AuthenticationTests = [
        ("testGoogleScope", testGoogleScope),
        ("testServiceAccountAuth", testServiceAccountAuth),
    ]
}

extension GMailTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GMailTests = [
        ("testMailFetch", testMailFetch),
        ("testMarkReadMessage", testMarkReadMessage),
        ("testMessages", testMessages),
        ("testParseMessage", testParseMessage),
        ("testProfile", testProfile),
        ("testReplyToMessage", testReplyToMessage),
        ("testSendMessage", testSendMessage),
        ("testTrash", testTrash),
    ]
}

extension IndexedSheetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IndexedSheetTests = [
        ("testBinarySearchValidity", testBinarySearchValidity),
        ("testLoadSheet", testLoadSheet),
        ("testManyOperations", testManyOperations),
        ("testSynchronize", testSynchronize),
    ]
}

extension SpreadsheetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpreadsheetTests = [
        ("testAppend", testAppend),
        ("testAppendRows", testAppendRows),
        ("testClearSheet", testClearSheet),
        ("testCreateSheet", testCreateSheet),
        ("testDelete", testDelete),
        ("testDeleteSheet", testDeleteSheet),
        ("testGetSpreadsheet", testGetSpreadsheet),
        ("testInsert", testInsert),
        ("testMove", testMove),
        ("testReadSheet", testReadSheet),
        ("testWrite", testWrite),
        ("testWriteRows", testWriteRows),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AtomicSheetTests.__allTests__AtomicSheetTests),
        testCase(AuthenticationTests.__allTests__AuthenticationTests),
        testCase(GMailTests.__allTests__GMailTests),
        testCase(IndexedSheetTests.__allTests__IndexedSheetTests),
        testCase(SpreadsheetTests.__allTests__SpreadsheetTests),
    ]
}
#endif
